# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Earl-Grey-Demo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Earl-Grey-Demo

  target 'Earl-Grey-DemoTests' do
    inherit! :search_paths
    use_frameworks!

    pod 'EarlGrey'
  end

end

post_install do |installer|
  require 'earlgrey'
  configure_for_earlgrey(installer, 'Earl-Grey-Demo', 'Earl-Grey-DemoTests', 'Earl-Grey-DemoTests', {swift: true})
end
